import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Yantronix AI — Product Listing Generator",
  description: "Paste a supplier URL and get a complete, SEO-optimized Zoho Commerce product listing generated by Gemini AI.",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
