import type { Metadata } from "next"
import "./globals.css"
import { checkAuth, loginAction } from "./auth-actions"
import { headers } from "next/headers"

export const metadata: Metadata = {
  title: "Yantronix AI — Product Listing Generator",
  description: "Paste a supplier URL and get a complete, SEO-optimized Zoho Commerce product listing generated by Gemini AI.",
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const isAuthenticated = await checkAuth()

  // Get error flag from URL if password was wrong
  const headersList = await headers()
  const referer = headersList.get('referer') || ''
  const hasError = referer.includes('auth_error=1')

  if (!isAuthenticated) {
    return (
      <html lang="en">
        <body>
          <style>{`
            *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
              display: flex; justify-content: center; align-items: center;
              min-height: 100vh; background: #0f0f11; color: #fff;
            }
            .card {
              background: #18181b; border: 1px solid #27272a;
              border-radius: 16px; padding: 2.5rem 2rem;
              box-shadow: 0 25px 60px rgba(0,0,0,0.6);
              width: 90%; max-width: 380px; text-align: center;
            }
            .lock { font-size: 2.5rem; margin-bottom: 1rem; }
            h1 { font-size: 1.3rem; font-weight: 600; margin-bottom: 0.4rem; }
            p { color: #71717a; font-size: 0.875rem; margin-bottom: 1.5rem; }
            .error {
              background: rgba(239,68,68,0.1); border: 1px solid rgba(239,68,68,0.3);
              color: #f87171; border-radius: 8px; padding: 0.6rem 0.75rem;
              font-size: 0.85rem; margin-bottom: 1rem;
            }
            input[type=password] {
              display: block; width: 100%; padding: 0.75rem 1rem;
              border-radius: 8px; border: 1px solid #27272a;
              background: #09090b; color: #fff; font-size: 1rem;
              margin-bottom: 0.75rem;
            }
            input[type=password]:focus {
              outline: 2px solid #3b82f6; outline-offset: 0;
            }
            button {
              display: block; width: 100%; padding: 0.75rem 1rem;
              background: #3b82f6; color: #fff; border: none;
              border-radius: 8px; font-size: 1rem; font-weight: 600;
              cursor: pointer;
            }
            button:hover { background: #2563eb; }
          `}</style>
          <div className="card">
            <div className="lock">🔒</div>
            <h1>Protected Access</h1>
            <p>This environment is private. Enter the password to continue.</p>
            {hasError && (
              <div className="error">Incorrect password. Please try again.</div>
            )}
            <form action={loginAction}>
              <input type="password" name="password" placeholder="Enter password" required autoFocus />
              <button type="submit">Unlock</button>
            </form>
          </div>
        </body>
      </html>
    )
  }

  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
